### ISSUE TITLE
I think that the lines to untar the file are not needed.

### ISSUE THREAD

**Issue by frederickjh** [xxh/xxh-plugin-zsh-powerlevel10k#1]
https://github.com/xxh/xxh-plugin-zsh-powerlevel10k/blob/10dba0fcd3dd8b55439a9a7b065074f0895fca6f/build.sh#L38-L39

I was looking at this file as an example while writing my own. It appears that powerlevel10k is being installed by shallow git clone. These lines are producing errors. Log output with Bash debug on and line numbers.

```bash
:42+tar -xzf powerlevel10k.git
tar (child): powerlevel10k.git: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
:43+rm powerlevel10k.git
rm: cannot remove 'powerlevel10k.git': No such file or directory
```

**Comment by anki-code** [comment]
Fixed. Thanks!
