### ISSUE TITLE
p10k configure: permission denied

### ISSUE THREAD

**Issue by pplmx** [xxh/xxh-plugin-zsh-powerlevel10k#2]
**Local OS (where xxh is installed):** macos
**Destination host OS:** ubuntu
**xxh version:** xxh/0.8.10
**xxh-plugins installed:** xxh-plugin-zsh-powerlevel10k

## Reproduce
1. `xxh yourhost`
2. `p10k configure`
3. the following error

![image](https://user-images.githubusercontent.com/26994103/178235743-d87e1961-6e53-4a0a-87b3-7502691559af.png)

**Comment by anki-code** [comment]
Nice catch @pplmx ! I've added setting the `TMPDIR` in xxh-shell-zsh - https://github.com/xxh/xxh-shell-zsh/commit/94f9f7c4e80962165179d1ebdd9eee6ec91047ff

Please try to update xxh-shell-zsh and try again i.e.
```python
xxh +RI xxh-shell-zsh
xxh host +if +s zsh
```

**Comment by pplmx** [comment]
> ```
> xxh +RI xxh-shell-zsh
> xxh host +if +s zsh
> ```

It's fine now. Thanks. :)
